-- ======================================================================
-- 100 - Loyal Customers
-- ======================================================================
-- Difficulty : Medium
-- Category   : Analytics
-- Companies  : Amazon
-- Access     : Premium
-- URL        : https://www.namastesql.com/coding-problems/100-loyal-customers
-- ======================================================================

/*
In the domain of retail analytics, understanding customer behavior is crucial for driving business growth and enhancing customer satisfaction. One essential aspect is identifying customers who have purchased all available products, as they exhibit strong engagement with the product offerings and represent potential loyal customers.
Write an SQL to identify customers who have bought all the products available in products table along with total revenue generated by them. Sort the output by total revenue in decreasing order.

 
Table:customers
+---------------+-------------+
| COLUMN_NAME   | DATA_TYPE   |
+---------------+-------------+
| customer_id   | int         |
| customer_name | varchar(15) |
+---------------+-------------+

Table:products
+--------------+-------------+
| COLUMN_NAME  | DATA_TYPE   |
+--------------+-------------+
| product_id   | int         |
| product_name | varchar(10) |
| unit_price   | int         |
+--------------+-------------+

Table:orders
+-------------+-----------+
| COLUMN_NAME | DATA_TYPE |
+-------------+-----------+
| order_id    | int       |
| customer_id | int       |
| product_id  | int       |
| quantity    | int       |
| order_date  | date      |
+-------------+-----------+
*/


-- Write your SQL solution below:

-- ============================================================
-- APPROACH 1: OPTIMIZED
-- (window functions, CTEs, efficient joins, minimal scans)
-- ============================================================

WITH customer_stats AS (
    SELECT 
        o.customer_id,
        -- Count distinct products purchased per customer
        COUNT(DISTINCT o.product_id) AS products_bought,
        -- Calculate total revenue: sum of quantity * unit_price
        SUM(o.quantity * p.unit_price) AS total_revenue
    FROM orders o
    JOIN products p ON o.product_id = p.product_id
    GROUP BY o.customer_id
),
total_products AS (
    SELECT COUNT(*) AS total_count FROM products
)
SELECT 
    c.customer_id,
    c.customer_name,
    cs.total_revenue
FROM customer_stats cs
JOIN customers c ON cs.customer_id = c.customer_id
CROSS JOIN total_products tp
-- Keep only customers who bought ALL available products
WHERE cs.products_bought = tp.total_count
ORDER BY cs.total_revenue DESC;

-- ============================================================
-- APPROACH 2: BRUTE FORCE
-- (subqueries, basic GROUP BY/HAVING, no window functions)
-- ============================================================

SELECT 
    c.customer_id,
    c.customer_name,
    SUM(o.quantity * p.unit_price) AS total_revenue
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN products p ON o.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name
HAVING 
    -- Customer must have purchased every product in the products table
    COUNT(DISTINCT o.product_id) = (SELECT COUNT(*) FROM products)
ORDER BY total_revenue DESC;
