-- ======================================================================
-- 189 - Campaigns Effectiveness ETL Pipeline
-- ======================================================================
-- Difficulty : Hard
-- Category   : ETL & Data Pipelines
-- Companies  : Practice question
-- Access     : Premium
-- URL        : https://www.namastesql.com/coding-problems/189-campaigns-effectiveness-etl-pipeline-0bab277a
-- ======================================================================

/*
A digital marketing team runs multiple campaigns (Email, Social, Push, etc.) and tracks how users interact with them.  You are provided three datasets:

campaigns.csv – campaign metadata
campaign_id, campaign_name, start_date, end_date, channel

web_visits.csv – user visits generated by campaigns
user_id, campaign_id, visit_timestamp

purchases.csv – user purchases
user_id, purchase_timestamp, purchase_amount

 

Your goal is to build an ETL pipeline that calculates the conversion rate and revenue metrics for each campaign.

 

Business Requirement

The company wants to understand which marketing campaign influenced each purchase.

Users may visit through multiple campaigns at different times and may also make multiple purchases.

To evaluate campaign performance, the company needs to determine which campaign should receive credit for each purchase.

 

The attribution rule used is:

A purchase should be assigned to the most recent campaign visit that happened before the purchase timestamp.

If a purchase has no earlier visit by the same user, it should be ignored because it cannot be attributed to any campaign.

Example:

Suppose a user has the following campaign visits:

Visited through campaign C1 on 2023-06-01 10:00

Visited through campaign C2 on 2023-06-03 09:30

Visited through campaign C3 on 2023-06-05 08:00

And the user made a purchase on:

Purchase at 2023-06-04 14:00

Before the purchase at 2023-06-04 14:00 the most recent campaign visit is C2 at 2023-06-03 09:30.

Therefore, this purchase is attributed to campaign C2.

 

Perform the following ETL operations to achieve this : 

1.Extract

Read all three CSV files into DataFrames.

2.Transform

A. Data Cleaning/ Remove Duplicates
Users can visit through the same campaign multiple times.
Keep only the latest visit for each (user_id, campaign_id) pair based on visit_timestamp.

 

B. Build Attribution Mapping
For each purchase, assign it to the campaign with the latest visit before the purchase timestamp.
If a purchase has no prior visit, ignore it.

 

C. Compute Campaign Metrics
For each campaign, calculate the following metrics:

unique_visitors – distinct users who visited the campaign
total_purchasers – distinct users who purchased after visiting
total_revenue – sum of purchase_amount
conversion_rate – total_purchasers * 100 / unique_visitors  - > (round to 2 decimal places)
 

 

3.Output

Print the final aggregated DataFrame with these columns:

campaign_name
unique_visitors
total_purchasers
total_revenue
conversion_rate
 

Sort the final output by total_revenue in descending order.
*/


-- Write your SQL solution below:

-- ============================================================
-- APPROACH 1: OPTIMIZED
-- (window functions, CTEs, efficient joins, minimal scans)
-- ============================================================

WITH deduped_visits AS (
    -- Keep only the latest visit per (user_id, campaign_id)
    SELECT DISTINCT ON (user_id, campaign_id)
        user_id,
        campaign_id,
        visit_timestamp
    FROM web_visits
    ORDER BY user_id, campaign_id, visit_timestamp DESC
),

attributed_purchases AS (
    -- For each purchase, find the most recent campaign visit before the purchase
    SELECT DISTINCT ON (p.user_id, p.purchase_timestamp)
        p.user_id,
        p.purchase_timestamp,
        p.purchase_amount,
        dv.campaign_id
    FROM purchases p
    JOIN deduped_visits dv
        ON dv.user_id = p.user_id
        AND dv.visit_timestamp < p.purchase_timestamp
    ORDER BY p.user_id, p.purchase_timestamp, dv.visit_timestamp DESC
    -- DISTINCT ON picks the row with the latest visit_timestamp per (user, purchase)
),

campaign_metrics AS (
    SELECT
        dv.campaign_id,
        COUNT(DISTINCT dv.user_id)                          AS unique_visitors,
        COUNT(DISTINCT ap.user_id)                          AS total_purchasers,
        COALESCE(SUM(ap.purchase_amount), 0)                AS total_revenue
    FROM deduped_visits dv
    LEFT JOIN attributed_purchases ap
        ON ap.campaign_id = dv.campaign_id
    GROUP BY dv.campaign_id
)

SELECT
    c.campaign_name,
    cm.unique_visitors,
    cm.total_purchasers,
    cm.total_revenue,
    ROUND(cm.total_purchasers * 100.0 / cm.unique_visitors, 2) AS conversion_rate
FROM campaign_metrics cm
JOIN campaigns c
    ON c.campaign_id = cm.campaign_id
ORDER BY cm.total_revenue DESC;


-- ============================================================
-- APPROACH 2: BRUTE FORCE
-- (subqueries, basic GROUP BY/HAVING, no window functions)
-- ============================================================

-- Step 1: Deduplicate visits - keep latest visit per (user_id, campaign_id)
-- Using a correlated subquery approach
SELECT
    c.campaign_name,
    visitors.unique_visitors,
    COALESCE(purchasers.total_purchasers, 0)  AS total_purchasers,
    COALESCE(purchasers.total_revenue, 0)     AS total_revenue,
    ROUND(
        COALESCE(purchasers.total_purchasers, 0) * 100.0 / visitors.unique_visitors,
        2
    ) AS conversion_rate
FROM campaigns c

-- unique visitors per campaign from deduplicated visits
JOIN (
    SELECT
        campaign_id,
        COUNT(DISTINCT user_id) AS unique_visitors
    FROM web_visits wv1
    WHERE visit_timestamp = (
        -- latest visit for this (user_id, campaign_id) pair
        SELECT MAX(wv2.visit_timestamp)
        FROM web_visits wv2
        WHERE wv2.user_id = wv1.user_id
          AND wv2.campaign_id = wv1.campaign_id
    )
    GROUP BY campaign_id
) AS visitors
    ON visitors.campaign_id = c.campaign_id

-- purchasers and revenue attributed to each campaign
LEFT JOIN (
    SELECT
        attr.campaign_id,
        COUNT(DISTINCT attr.user_id)   AS total_purchasers,
        SUM(attr.purchase_amount)      AS total_revenue
    FROM (
        -- For each purchase, find the campaign_id of the most recent prior visit
        SELECT
            p.user_id,
            p.purchase_amount,
            (
                SELECT wv.campaign_id
                FROM web_visits wv
                WHERE wv.user_id = p.user_id
                  AND wv.visit_timestamp < p.purchase_timestamp
                  -- only consider the latest deduplicated visit per campaign
                  AND wv.visit_timestamp = (
                      SELECT MAX(wv2.visit_timestamp)
                      FROM web_visits wv2
                      WHERE wv2.user_id = wv.user_id
                        AND wv2.campaign_id = wv.campaign_id
                  )
                ORDER BY wv.visit_timestamp DESC
                LIMIT 1
            ) AS campaign_id
        FROM purchases p
    ) AS attr
    WHERE attr.campaign_id IS NOT NULL  -- ignore purchases with no prior visit
    GROUP BY attr.campaign_id
) AS purchasers
    ON purchasers.campaign_id = c.campaign_id

ORDER BY total_revenue DESC;
