-- ======================================================================
-- 100 - Loyal Customers
-- ======================================================================
-- Difficulty : Medium
-- Category   : Analytics
-- Companies  : Amazon
-- Access     : Premium
-- URL        : https://www.namastesql.com/coding-problems/100-loyal-customers
-- ======================================================================

/*
In the domain of retail analytics, understanding customer behavior is crucial for driving business growth and enhancing customer satisfaction. One essential aspect is identifying customers who have purchased all available products, as they exhibit strong engagement with the product offerings and represent potential loyal customers.
Write an SQL to identify customers who have bought all the products available in products table along with total revenue generated by them. Sort the output by total revenue in decreasing order.

 
Table:customers
+---------------+-------------+
| COLUMN_NAME   | DATA_TYPE   |
+---------------+-------------+
| customer_id   | int         |
| customer_name | varchar(15) |
+---------------+-------------+

Table:products
+--------------+-------------+
| COLUMN_NAME  | DATA_TYPE   |
+--------------+-------------+
| product_id   | int         |
| product_name | varchar(10) |
| unit_price   | int         |
+--------------+-------------+

Table:orders
+-------------+-----------+
| COLUMN_NAME | DATA_TYPE |
+-------------+-----------+
| order_id    | int       |
| customer_id | int       |
| product_id  | int       |
| quantity    | int       |
| order_date  | date      |
+-------------+-----------+
*/


-- Write your SQL solution below:

```sql
SELECT 
    c.customer_id,
    c.customer_name,
    SUM(o.quantity * p.unit_price) AS total_revenue
FROM customers c
INNER JOIN orders o ON c.customer_id = o.customer_id
INNER JOIN products p ON o.product_id = p.product_id
GROUP BY c.customer_id, c.customer_name
-- Filter for customers whose distinct product count equals total products available
HAVING COUNT(DISTINCT o.product_id) = (SELECT COUNT(*) FROM products)
ORDER BY total_revenue DESC;
```
