-- ======================================================================
-- 189 - Campaigns Effectiveness ETL Pipeline
-- ======================================================================
-- Difficulty : Hard
-- Category   : ETL & Data Pipelines
-- Companies  : Practice question
-- Access     : Premium
-- URL        : https://www.namastesql.com/coding-problems/189-campaigns-effectiveness-etl-pipeline-0bab277a
-- ======================================================================

/*
A digital marketing team runs multiple campaigns (Email, Social, Push, etc.) and tracks how users interact with them.  You are provided three datasets:

campaigns.csv – campaign metadata
campaign_id, campaign_name, start_date, end_date, channel

web_visits.csv – user visits generated by campaigns
user_id, campaign_id, visit_timestamp

purchases.csv – user purchases
user_id, purchase_timestamp, purchase_amount

 

Your goal is to build an ETL pipeline that calculates the conversion rate and revenue metrics for each campaign.

 

Business Requirement

The company wants to understand which marketing campaign influenced each purchase.

Users may visit through multiple campaigns at different times and may also make multiple purchases.

To evaluate campaign performance, the company needs to determine which campaign should receive credit for each purchase.

 

The attribution rule used is:

A purchase should be assigned to the most recent campaign visit that happened before the purchase timestamp.

If a purchase has no earlier visit by the same user, it should be ignored because it cannot be attributed to any campaign.

Example:

Suppose a user has the following campaign visits:

Visited through campaign C1 on 2023-06-01 10:00

Visited through campaign C2 on 2023-06-03 09:30

Visited through campaign C3 on 2023-06-05 08:00

And the user made a purchase on:

Purchase at 2023-06-04 14:00

Before the purchase at 2023-06-04 14:00 the most recent campaign visit is C2 at 2023-06-03 09:30.

Therefore, this purchase is attributed to campaign C2.

 

Perform the following ETL operations to achieve this : 

1.Extract

Read all three CSV files into DataFrames.

2.Transform

A. Data Cleaning/ Remove Duplicates
Users can visit through the same campaign multiple times.
Keep only the latest visit for each (user_id, campaign_id) pair based on visit_timestamp.

 

B. Build Attribution Mapping
For each purchase, assign it to the campaign with the latest visit before the purchase timestamp.
If a purchase has no prior visit, ignore it.

 

C. Compute Campaign Metrics
For each campaign, calculate the following metrics:

unique_visitors – distinct users who visited the campaign
total_purchasers – distinct users who purchased after visiting
total_revenue – sum of purchase_amount
conversion_rate – total_purchasers * 100 / unique_visitors  - > (round to 2 decimal places)
 

 

3.Output

Print the final aggregated DataFrame with these columns:

campaign_name
unique_visitors
total_purchasers
total_revenue
conversion_rate
 

Sort the final output by total_revenue in descending order.
*/


-- Write your SQL solution below:

```sql
-- Extract: Create tables from CSV files
-- Assuming data is loaded into campaigns, web_visits, and purchases tables

-- Transform: Step A - Remove duplicates, keeping latest visit per (user_id, campaign_id)
WITH latest_visits AS (
  SELECT 
    user_id,
    campaign_id,
    visit_timestamp,
    ROW_NUMBER() OVER (PARTITION BY user_id, campaign_id ORDER BY visit_timestamp DESC) AS rn
  FROM web_visits
)
,
cleaned_visits AS (
  SELECT 
    user_id,
    campaign_id,
    visit_timestamp
  FROM latest_visits
  WHERE rn = 1
)
,
-- Transform: Step B - Build attribution mapping
-- For each purchase, find the most recent campaign visit before the purchase
attributed_purchases AS (
  SELECT 
    p.user_id,
    p.purchase_timestamp,
    p.purchase_amount,
    cv.campaign_id,
    ROW_NUMBER() OVER (PARTITION BY p.user_id, p.purchase_timestamp ORDER BY cv.visit_timestamp DESC) AS rn
  FROM purchases p
  LEFT JOIN cleaned_visits cv 
    ON p.user_id = cv.user_id 
    AND cv.visit_timestamp < p.purchase_timestamp
  WHERE cv.campaign_id IS NOT NULL
)
,
final_attribution AS (
  SELECT 
    user_id,
    purchase_timestamp,
    purchase_amount,
    campaign_id
  FROM attributed_purchases
  WHERE rn = 1
)
,
-- Transform: Step C - Compute campaign metrics
campaign_metrics AS (
  SELECT 
    c.campaign_id,
    c.campaign_name,
    COUNT(DISTINCT cv.user_id) AS unique_visitors,
    COUNT(DISTINCT fa.user_id) AS total_purchasers,
    COALESCE(SUM(fa.purchase_amount), 0) AS total_revenue,
    ROUND(
      CASE 
        WHEN COUNT(DISTINCT cv.user_id) = 0 THEN 0
        ELSE (COUNT(DISTINCT fa.user_id) * 100.0 / COUNT(DISTINCT cv.user_id))
      END,
      2
    ) AS conversion_rate
  FROM campaigns c
  LEFT JOIN cleaned_visits cv ON c.campaign_id = cv.campaign_id
  LEFT JOIN final_attribution fa ON c.campaign_id = fa.campaign_id
  GROUP BY c.campaign_id, c.campaign_name
)
-- Output: Final result sorted by total_revenue descending
SELECT 
  campaign_name,
  unique_visitors,
  total_purchasers,
  total_revenue,
  conversion_rate
FROM campaign_metrics
ORDER BY total_revenue DESC;
```
